export const demoThemes = [
  {
    id: 'martial-arts',
    label: 'Martial Arts Gym',
    businessName: 'Apex Martial Arts',
    logo: 'AM',
    accent: '#8B2FC9',
    heroImage: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1400&q=80',
    headline: 'A sharper online home for your martial arts gym',
    subheadline: 'Show your classes, collect waivers, manage trials, track members and give coaches the admin tools they need.',
    servicesTitle: 'Class Schedule',
    services: ['Kids classes', 'Beginner programme', 'Striking fundamentals', 'Grappling sessions', 'Open mat', 'Private coaching'],
    pricingWording: 'Memberships, free trials, drop-ins and limited weekly plans can all be tailored to your gym.',
    testimonial: 'The system feels like it was built around how a real gym runs.',
    contact: { email: 'hello@apexdemo.example', phone: '0800 111 000', instagram: '@apexdemo' },
    gallery: [
      'https://images.unsplash.com/photo-1517438322307-e67111335449?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 'running-club',
    label: 'Running Club',
    businessName: 'Northside Runners',
    logo: 'NR',
    accent: '#2F80ED',
    heroImage: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=80',
    headline: 'Turn interest into registered runners',
    subheadline: 'Promote training nights, manage sign-ups, take event interest and keep members updated from one simple system.',
    servicesTitle: 'Upcoming Events',
    services: ['Beginner couch-to-5k', 'Weekly road runs', 'Trail sessions', 'Race registration', 'Volunteer list', 'Club updates'],
    pricingWording: 'Event registration, yearly memberships and waiting lists can be adapted for your club.',
    testimonial: 'It made the club look organised before anyone even joined.',
    contact: { email: 'hello@runnersdemo.example', phone: '0800 222 000', instagram: '@runnersdemo' },
    gallery: [
      'https://images.unsplash.com/photo-1502904550040-7534597429ae?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 'football-club',
    label: 'Football Club',
    businessName: 'Town United FC',
    logo: 'TU',
    accent: '#24A148',
    heroImage: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1400&q=80',
    headline: 'A professional website for your club and teams',
    subheadline: 'Handle player registration, fixtures, enquiries, team updates and admin without stitching together spreadsheets.',
    servicesTitle: 'Fixtures & Teams',
    services: ['Player registration', 'Youth teams', 'Senior fixtures', 'Training nights', 'Volunteer forms', 'Sponsor area'],
    pricingWording: 'Player forms, season fees, team lists and club notices can be configured around your season.',
    testimonial: 'Parents and players finally had one place to go.',
    contact: { email: 'hello@footballclubdemo.example', phone: '0800 333 000', instagram: '@footballclubdemo' },
    gallery: [
      'https://images.unsplash.com/photo-1556056504-5c7696c4c28d?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 'fitness-studio',
    label: 'Fitness Studio',
    businessName: 'Core Studio',
    logo: 'CS',
    accent: '#F97316',
    heroImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=80',
    headline: 'Sell classes, trials and transformations online',
    subheadline: 'Show your timetable, collect enquiries, manage members and give your studio a premium first impression.',
    servicesTitle: 'Studio Services',
    services: ['Group classes', 'Transformation plans', 'Strength blocks', 'Mobility sessions', 'Trial week', 'Member check-ins'],
    pricingWording: 'Class packs, monthly memberships and intro offers can be worded around your studio model.',
    testimonial: 'The demo instantly looked like a real studio brand.',
    contact: { email: 'hello@corestudiodemo.example', phone: '0800 444 000', instagram: '@corestudiodemo' },
    gallery: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 'personal-trainer',
    label: 'Personal Trainer',
    businessName: 'Coach Morgan',
    logo: 'CM',
    accent: '#DC2626',
    heroImage: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=1400&q=80',
    headline: 'A booking-ready site for your coaching business',
    subheadline: 'Promote programmes, capture consultation requests, manage clients and look established from day one.',
    servicesTitle: 'Coaching Options',
    services: ['1:1 coaching', 'Online coaching', 'Nutrition check-ins', 'Small group training', 'Consultation call', 'Progress tracking'],
    pricingWording: 'Consultation bookings, monthly coaching packages and client forms can be adapted to your offer.',
    testimonial: 'It gave my coaching offer structure and made enquiries easier to handle.',
    contact: { email: 'hello@coachdemo.example', phone: '0800 555 000', instagram: '@coachdemo' },
    gallery: [
      'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1550345332-09e3ac987658?auto=format&fit=crop&w=900&q=80',
    ],
  },
  {
    id: 'local-business',
    label: 'Local Business',
    businessName: 'Harbour Services',
    logo: 'HS',
    accent: '#1E3A8A',
    heroImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80',
    headline: 'A polished website and enquiry system for local services',
    subheadline: 'Show what you do, capture leads, organise customer requests and give your business a more professional online presence.',
    servicesTitle: 'Service Enquiries',
    services: ['Service pages', 'Quote requests', 'Customer messages', 'Gallery', 'Testimonials', 'Admin follow-up'],
    pricingWording: 'Service lists, quote forms, booking wording and contact flows can match your business.',
    testimonial: 'It made the business look bigger, clearer and easier to contact.',
    contact: { email: 'hello@localdemo.example', phone: '0800 666 000', instagram: '@localdemo' },
    gallery: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80',
    ],
  },
];
